language: python
matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON=2.7
  - os: osx
    language: generic
    env: PYTHON=3.4
  - os: osx
    language: generic
    env: PYTHON=3.5
  - os: osx
    language: generic
    env: PYTHON=3.6
  - os: linux
    language: generic
    env: PYTHON=2.7
  - os: linux
    language: generic
    env: PYTHON=3.4
  - os: linux
    language: generic
    env: PYTHON=3.5
  - os: linux
    language: generic
    env: PYTHON=3.6
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then if [[ "$PYTHON" == "2.7" ]]; then wget
  http://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
  else wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
  -O miniconda.sh; fi else if [[ "$PYTHON" == "2.7" ]]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
# Note bug noted here: https://github.com/cython/cython/issues/1953 might require cython=0.25.2
- conda create -q -n test-environment python=$PYTHON cython
- source activate test-environment
# - pip install -r dev-requirements.txt
install:
- (cd shrubbery ; python setup.py install)
- (cd landscaping ; python setup.py install)
script:
- python -c 'from landscaping.landscaping import test ; test()'
